spring.application.name=api3-backend
# Ativa o console do H2
spring.h2.console.enabled=true

# Define o caminho para acessar (opcional, o padrão já é /h2-console)
spring.h2.console.path=/h2-console

# Configurações do Banco em Memória (Importante para o H2 não mudar o nome toda hora)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect